# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65ff6801ec85615da615d5140efe17109ee9529dfb52b2a2c81ee904a41f89add649d08a19471be0ad87955ce69db1345cac549debf7a2dee9993ab6304c49ef

test:
  secret_key_base: 0ff629859e9f96e4abdc5c0ad844637ddef077f414fef1676cbc4e807fa478658cf5b2bc06353fd73dbb523380d5650d80cffdc5203f1e12bbc036e73b04e274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
