# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6e6a7e01eff0fe9c531257e6fd4935a816dfd6b947af490d4eab0df1a56008b7e9018a73fbe4876a7f1a9d836bf014be02924aa9c6f84619fa461bf13f02684

test:
  secret_key_base: 0962a41fe9d1fb04160ca5740e18baf4018b37c4f09b95390c1ea347c28ad9f5378443bb9bf194b83e5eb4080d80da7853561d86467bbc405bbcba9cc23764a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
